stages:
- name: compile
  steps:
  - runScriptConfig:
      image: reg.aiyinsitanfm.com/application/maven3.5.4:20181018
      shellScript: mvn clean package
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: gsafety/demo:v1
      pushRemote: true
      registry: reg.aiyinsitanfm.com
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
timeout: 60
